name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test_and_caption:
    runs-on: ubuntu-latest
    env:
      # your service account JSON must be stored here
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      # 1) checkout & test
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest --maxfail=1 --disable-warnings -q

      # 2) configure GCP credentials
      - name: Write service‑account key to disk
        run: |
          echo "${GCP_SA_KEY}" > "$HOME/gcp-sa.json"
          chmod 600 "$HOME/gcp-sa.json"

      - name: Point at Service Account
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-sa.json" >> $GITHUB_ENV

      # 3) generate captions from consolidated CSV
      - name: Generate captions from consolidated_output.csv
        run: |
          # Make sure the consolidated CSV exists. If you have a separate workflow,
          # you must download it here via `actions/download-artifact`, or produce
          # it in this job before this step.
          ls consolidated_output.csv

          # Run the caption agent using the new --input flag
          python caption_agent.py \
            --input consolidated_output.csv \
            --n 12

      # 4) upload the captions CSV as an artifact
      - name: Upload captions artifact
        uses: actions/upload-artifact@v4
        with:
          name: captions-consolidated
          path: captions_consolidated_output.csv
