# .github/workflows/run-google-trends.yml
name: Run Google Trends Agent

on:
  schedule:
    # 00 UTC daily
    - cron: '0 12 * * *'
  workflow_dispatch:        # manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    # ────────────────────────────────
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # ───── Install dependencies ─────
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-bigquery python-dotenv pandas db-dtypes tabulate openai

    # ───── Restore GCP key (from repo/Org secrets) ─────
    - name: Restore GCP key
      run: |
        echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d > key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"  >> $GITHUB_ENV

    # ───── Run the bot ─────
    - name: Run trend bot
      run: |
        python trend_bot.py

    # ───── List generated CSVs ─────
    - name: List generated CSV
      run: |
        ls -lh trend_*_*.csv      # matches trend_rising_*.csv & trend_top_*.csv

    # ───── Show CSV content in logs (optional, tiny preview) ─────
    - name: Show CSV preview
      run: |
        echo "=== Rising CSV head ==="
        head -n 5 trend_rising_*_*.csv
        echo "=== Top CSV head ==="
        head -n 5 trend_top_*_*.csv

    # ───── Upload CSVs as artifact ─────
    - name: Upload CSVs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trend-bot-output
        path: trend_*_*.csv
