name: Run Twitter Agent

on:
 # schedule:
  #  - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:       # manual trigger only

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium  

      - name: Ensure CSV file exists
        run: touch trends_output.csv

      - name: Run Twitter Agent
        run: python twitter_agent.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: trends-output
          path: trends_output.csv
