name: Daily Google-Trends Bot

on:
  schedule:
    - cron: '0 12 * * *'      # 12:00 UTC daily
  workflow_dispatch:          # manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-bigquery python-dotenv pandas db-dtypes tabulate openai

    - name: Restore GCP key
      run: |
        echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d > key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

    - name: Run trend bot
      run: |
        python trend_bot.py

    - name: List generated CSV
      run: |
        ls -lh trend_output_*.csv

    - name: Show CSV content in logs
      run: |
        echo "==== Trend Bot CSV Output ===="
        cat trend_output_*.csv

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trend-bot-output
        path: trend_output_*.csv
