name: Run Google Trends Agent

on:
 # schedule:
 #   - cron:  '0 12 * * *'          # 12:00 UTC daily
  workflow_dispatch:               # manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    # 1 – check out repo
    - uses: actions/checkout@v4

    # 2 – set up Python
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3 – install deps
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-bigquery python-dotenv pandas db-dtypes tabulate openai

    # 4 – restore GCP key (→ $GITHUB_ENV)
    - name: Restore GCP key
      run: |
        echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d > key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json" >> $GITHUB_ENV

    # 5 – run the bot (writes CSVs)
    - name: Run trend bot
      run: python trend_bot.py

    # 6 – list whatever was created (never fails)
    - name: List generated CSV
      run: ls -lh trend_*_*.csv || true

    # 7 – preview the files (never fails)
    - name: Show CSV preview
      run: |
        echo "=== Rising CSV head ==="
        (head -n 5 trend_rising_*_*.csv 2>/dev/null || echo "No rising CSV")
        echo "=== Top CSV head ==="
        (head -n 5 trend_top_*_*.csv 2>/dev/null || echo "No top CSV")

    # 8 – upload whatever CSVs exist
    - name: Upload CSVs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trend-bot-output
        path: trend_*_*.csv
        if-no-files-found: warn     # don’t fail when empty
