name: run reddit agent

# grant write access so we can push back to the repo
permissions:
  contents: write

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        # ensure we use the GITHUB_TOKEN
       persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pandas

    - name: Fetch 1 000 Reddit posts
      env:
        REDDIT_CLIENT_ID:     ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT:    ${{ secrets.REDDIT_USER_AGENT }}
      run: python reddit_agent.py

    - name: Upload CSV artifact
      uses: actions/upload-artifact@v4
      with:
        name: reddit-csv
        path: reddit_hot_posts.csv
