name: Scrape TikTok Hashtags

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:       # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-22.04
    
    env:
      SUPABASE_URL: https://haz22zel's Project.supabase.co
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlcWxjaWt4Zm91Z21nYWh3eWl0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDcxMjM0NSwiZXhwIjoyMDY2Mjg4MzQ1fQ.bHxA3Vo5flNTorS6lTUHdQ1kBSbT-pshty78EtAVJ-c
      
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run script with xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          xvfb-run python tiktok_hashtag_test.py

      - name: Upload CSV and Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: tiktok-hashtag-output
          path: |
            tiktok_hashtags.csv
            tiktok_hashtag_landing.png
            error_screenshot.png
